language: php
php:
    - '7.1.7'

script:
    - phpunit galleryModule/testGalleryClass.php
    
before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    #- phpunit --bootstrap test/config.php test
    - phpunit  galleryModule/testGalleryClass.php --coverage-clover coverage.clover test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
