language: php
php:
    - '7.1.7'
    
before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - phpunit galleryModule/testGalleryClass.php
    - phpunit --coverage-clover= galleryModule/testGalleryClass.php

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
